services:
  curator:
    container_name: ${CONTAINER_PREFIX}-curator
    build:
      context: docker/extensions/curator/
    init: true
    volumes:
      - ./docker/extensions/curator/config/curator.yml:/.curator/curator.yml:ro,Z
      - ./docker/extensions/curator/config/delete_log_files_curator.yml:/.curator/delete_log_files_curator.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - app
    depends_on:
      - elasticsearch
