# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  
  # Note that the session will be started ONLY if you read or write from it.
  session: true
  
  #esi: true
  #fragments: true
  http_client:
    scoped_clients:
      es.client:
        base_uri: http://host.docker.internal:9200
        auth_basic: "%env(string:ELASTIC_USER)%:%env(string:ELASTIC_PASSWORD)%"

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
