monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      buffer_size: 50
    nested:
      type: stream
      level: debug
      formatter: 'monolog.formatter.logstash'
      max_files: 3
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      deprecation:
        type: stream
        channels: [ deprecation ]
        path: php://stderr
        formatter: monolog.formatter.json
