version: '3.9'

networks:
  default:
    driver: bridge

x-logging-rules: &logging-rules
  logging:
    driver: "json-file"
    options:
      max-size: 20m
      max-file: "5"

volumes:
  php_socket:
  database:
    driver: local

services:
  ### php-fpm ###
  php-fpm:
    container_name: php-fpm
    build:
      context: deploy/php
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
      dockerfile: Dockerfile
    #command: 'sh -c "cd /var/www/app && composer install --no-interaction --prefer-dist --optimize-autoloader && php bin/console doctrine:migrations:migrate && php-fpm"'
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file:
      - ${APP_CODE_PATH_HOST}/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8mb4}
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8080:80'
    <<: *logging-rules

  ### NGINX Server ###
  nginx:
    container_name: nginx
    image: nginx:1.22.1
    volumes:
      - ${APP_CODE_PATH_HOST}/deploy/nginx/conf.d/:/etc/nginx/conf.d/
      - ${APP_CODE_PATH_HOST}/deploy/nginx_logs:/var/log/nginx/
      - ${APP_CODE_PATH_HOST}:/var/www/app
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - php-fpm
    networks:
      - default
    <<: *logging-rules

  ### Mysql database ###
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-15}
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    volumes:
      - database:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default
    <<: *logging-rules

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9443:9443'
      - '9000:9000'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    networks:
      - default
    <<: *logging-rules
