[supervisord]
nodaemon=true
[program:symfony-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /srv/app/bin/console messenger:consume async --time-limit=3600 -vv
autostart=true
autorestart=true
numprocs=2
startretries=10
user=www-data
redirect_stderr=true
stdout_logfile=/srv/app/var/log/symfony-queue-worker.log
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock;
