resources:
  App\Entity\Product:
    shortName: 'Product'
    description: 'An product from my shop'
    types: [
      'https://schema.org/Product'
    ]
    paginationItemsPerPage: 25
    operations:
      get_products:
        class: ApiPlatform\Metadata\GetCollection
        routeName: products_collection
        openapi:
          summary: Get bunch of products
          description: This method provide you to get bunch of product!
      create_product:
        class: ApiPlatform\Metadata\Post
        routeName: create_product
        openapi:
          summary: Create product
          description: This method provide you to create new product!
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name: { type: string }
                example:
                  name: Iphone 15
      get_product:
        class: ApiPlatform\Metadata\Get
        routeName: get_product
        openapi:
          summary: Get product
          description: This method provide you to get exist product!
      update_product:
        class: ApiPlatform\Metadata\Put
        routeName: update_product
        openapi:
          summary: Update product
          description: This method provide you to update exist product!
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name: { type: string }
                example:
                  name: Iphone 15
      patch_product:
        class: ApiPlatform\Metadata\Patch
        routeName: edit_product
        openapi:
          summary: Patch product
          description: This method provide you to patch exist product!
          requestBody:
            required: true
            content:
              application/merge-patch+json:
                schema:
                  type: object
                  properties:
                    name: { type: string }
                example:
                  name: Iphone 15
      delete_product:
        class: ApiPlatform\Metadata\Delete
        routeName: delete_product
        openapi:
          summary: Delete product
          description: This method provide you to delete exist product!
  App\Entity\Offer:
    shortName: 'Offer'
    description: 'An offer from my shop'
    types: ['https://schema.org/Offer']
    paginationItemsPerPage: 25
    operations:
      get_offers:
        class: ApiPlatform\Metadata\GetCollection
        routeName: offers_collection
        openapi:
          summary: Get bunch of offers
          description: This method provide you to get bunch of offers!
      create_offer:
        class: ApiPlatform\Metadata\Post
        routeName: create_offer
        openapi:
          summary: Create offer
          description: This method provide you to create new offer!
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    description: { type: string }
                    price: { type: float }
                    product: { type: int }
                example:
                  description: Ohh my god, wow
                  price: 1.0
                  product: 1
      get_offer:
        class: ApiPlatform\Metadata\Get
        routeName: get_offer
        openapi:
          summary: Get offer
          description: This method provide you to get exist offer!
      update_offer:
        class: ApiPlatform\Metadata\Put
        routeName: update_offer
        openapi:
          summary: Update product
          description: This method provide you to update exist offer!
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    description: { type: string }
                    price: { type: float }
                    product: { type: string }
                example:
                  description: Ohh my god, wow
                  price: 1.0
                  product: '/api/products/1'
      patch_offer:
        class: ApiPlatform\Metadata\Patch
        routeName: edit_offer
        openapi:
          summary: Patch offer
          description: This method provide you to patch exist offer!
          requestBody:
            required: true
            content:
              application/merge-patch+json:
                schema:
                  type: object
                  properties:
                    description: { type: string }
                    price: { type: float }
                    product: { type: string }
                example:
                  description: Ohh my god, wow
                  price: 1.0
                  product: '/api/products/1'
      delete_offer:
        class: ApiPlatform\Metadata\Delete
        routeName: delete_offer
        openapi:
          summary: Delete offer
          description: This method provide you to delete exist offer!
